<?php

use Illuminate\Database\Seeder;
use App\Models\Diocese;

class DioceseTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
	    $diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Manaus';
	    $diocese->save();
	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Coari';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Prelazia de Borba';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Alto Solimões';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Prelazia de Tefé';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Parintins';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Prelazia de Itacoatiara';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de São Gabriel da Cachoeira';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Roraima';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Óbidos';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Prelazia do Xingu';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Santarém';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Prelazia de Marajó';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Marabá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Bragança do Pará';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Castanhal';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Abaetetuba';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Cametá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Ponta de Pedras';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Santíssima Conceição do Araguaia';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Macapá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Palmas';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Prelazia de Cristalândia';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Miracema do Tocantins';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Porto Nacional';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Tocantinópolis';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Tocantinópolis';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Quixadá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Iguatu';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Tianguá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese do Crato';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Crateús';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Limoeiro do Norte';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Sobral';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Itapipoca';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Olinda e Recife';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Nazaré';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Petrolina';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Caruaru';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Garanhuns';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Floresta';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Palmares';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Afogados da Ingazeira';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Pesqueira';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Salgueiro';
	    $diocese->save();
// Centro-Oeste
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Goiânia ';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Rubiataba-Mozarlândia';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Jataí';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Goiás';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Anápolis';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Itumbiara';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Ipameri';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de São Luís de Montes Belos';
	    $diocese->save();
  	   	$diocese = new Diocese();
// Centro-Oeste  	   	
	    $diocese->no_diocese = 'Arquidiocese de Brasília';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Uruaçu ';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Luziânia';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Formosa';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Campo Grande';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Corumbá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Coxim';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Dourados';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Jardim';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Naviraí';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Três Lagoas';
	    $diocese->save();
//Seguir com Regional Oeste 2 (Mato Grosso)
    }
}
