<?php

use Illuminate\Database\Seeder;
use App\Models\Diocese;

class DioceseTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
	    $diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Manaus';
	    $diocese->save();
	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Coari';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Prelazia de Borba';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Alto Solimões';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Prelazia de Tefé';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Parintins';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Prelazia de Itacoatiara';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de São Gabriel da Cachoeira';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Roraima';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Óbidos';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Prelazia do Xingu';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Santarém';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Prelazia de Marajó';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Marabá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Bragança do Pará';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Castanhal';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Abaetetuba';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Cametá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Ponta de Pedras';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Santíssima Conceição do Araguaia';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Macapá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Palmas';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Prelazia de Cristalândia';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Miracema do Tocantins';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Porto Nacional';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Tocantinópolis';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Tocantinópolis';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Quixadá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Iguatu';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Tianguá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese do Crato';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Crateús';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Limoeiro do Norte';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Sobral';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Itapipoca';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Olinda e Recife';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Nazaré';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Petrolina';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Caruaru';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Garanhuns';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Floresta';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Palmares';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Afogados da Ingazeira';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Pesqueira';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Salgueiro';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese da Paraíba';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Guarabira';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Campina Grande';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Patos';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Cajazeiras';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Maceió';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Palmeira dos Índios';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Penedo';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Natal';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Mossoró';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Caicó';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de São Salvador da Bahia ';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Amargosa';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Itabuna';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Ilhéus';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Eunápolis';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Alagoinhas';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Teixeira de Freitas-Caravelas';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Camaçari';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Cruz das Almas';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Vitória da Conquista';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Jequié';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Bom Jesus da Lapa';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Caetité';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Livramento de Nossa Senhora';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Feira de Santana';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Bonfim';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Barreiras';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Ruy Barbosa';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Barra';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Paulo Afonso';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Irecê';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Juazeiro';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Serrinha';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Aracaju';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Propriá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Estância';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Teresina';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Oeiras';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Floriano';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Bom Jesus do Gurguéia';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Campo Maior';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Parnaíba';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Picos';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de São Raimundo Nonato';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de São Luís do Maranhão ';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Coroatá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Pinheiro';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Caxias do Maranhão';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Brejo';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Viana';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Balsas';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Grajaú';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Bacabal';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Carolina';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Zé-Doca';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Imperatriz';
	    $diocese->save();
		// Aqui comecei a cadastrar as arquidioceses - Parei na Nordeste 5
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de São Sebastião do Rio de Janeiro';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Niterói';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Mariana';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Diamantina';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Belo Horizonte';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Pouso Alegre';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Uberaba';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Juiz de Fora';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Montes Claros';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Vitória';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de São Paulo';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Botucatu';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Campinas';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Ribeirão Preto';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Aparecida';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Sorocaba';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Curitiba';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Lodrina';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Maringá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Cascavel';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Porto Alegre';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Pelotas';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Santa Maria';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Passo Fundo';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Florianópolis';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Cuiabá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Porto Velho';
	    $diocese->save();
// Parei aqui com as Arquidioceses
// Centro-Oeste
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Goiânia ';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Rubiataba-Mozarlândia';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Jataí';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Goiás';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Anápolis';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Itumbiara';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Ipameri';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de São Luís de Montes Belos';
	    $diocese->save();
  	   	$diocese = new Diocese();
// Centro-Oeste  	   	
	    $diocese->no_diocese = 'Arquidiocese de Brasília';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Uruaçu ';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Luziânia';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Formosa';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Arquidiocese de Campo Grande';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Corumbá';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Coxim';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Dourados';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Jardim';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Naviraí';
	    $diocese->save();
  	   	$diocese = new Diocese();
	    $diocese->no_diocese = 'Diocese de Três Lagoas';
	    $diocese->save();
//Seguir com Regional Oeste 2 (Mato Grosso)
    }
}
